### PR TITLE
[WIP] Revert to using pytomlpp

### PR DESCRIPTION
**Pull request by bobfang1992**
Want to try this to see what's going on

### CODE REVIEW

**Comment by bobfang1992** [comment]
Ah sorry this seems not triggering the CI

**Comment by marzer** [comment]
> this seems not triggering the CI

D:

It's supposed to! Lemme look into it. Guess I don't have this repo configured correctly.

**Comment by marzer** [comment]
@bobfang1992 it should be OK now, try force-pushing again

**Comment by bobfang1992** [comment]
Hi do you mind approving the run? Thanks!

**Comment by marzer** [comment]
Interesting, it seems to work OK now O_o

I think I might leave it as using tomli for the time being since poxy isn't perf-critical in any meaningful way (it will still preferentially use pytomlpp [if it's available](https://github.com/marzer/poxy/blob/39faea80911ea85e68d63c5e3653bfac831faee2/poxy/project.py#L12-L18))

**Pull request closed without merging**
